/*
** $Id: LPP.c $
** LPP (LPP++) stand-alone interpreter
** Copyright (C) 2024-2025 Klinti Karaj, Albania
** See Copyright Notice in LPP.h
*/

#define LPP_c

#include "lppprefix.h"


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <signal.h>

#include "lpp.h"

#include "lppauxlib.h"
#include "lpplib.h"


#if !defined(LPP_PROGNAME)
#define LPP_PROGNAME		"LPP"
#endif

#if !defined(LPP_INIT_VAR)
#define LPP_INIT_VAR		"LPP_INIT"
#endif

#define LPP_INITVARVERSION	LPP_INIT_VAR LPP_VERSUFFIX


static LUA_State *globalL = NULL;

static const char *progname = LPP_PROGNAME;


#if defined(LUA_USE_POSIX)   /* { */

/*
** Use 'sigaction' when available.
*/
static void setsignal (int sig, void (*handler)(int)) {
  struct sigaction sa;
  sa.sa_handler = handler;
  sa.sa_flags = 0;
  sigemptyset(&sa.sa_mask);  /* do not mask any signal */
  sigaction(sig, &sa, NULL);
}

#else           /* }{ */

#define setsignal            signal

#endif                               /* } */


/*
** Hook set by signal function to stop the interpreter.
*/
static void lstop (LUA_State *L, LPP_Debug *ar) {
  (void)ar;  /* unused arg. */
  LPP_sethook(L, NULL, 0, 0);  /* reset hook */
  LPPL_error(L, "interrupted!");
}


/*
** Function to be called at a C signal. Because a C signal cannot
** just change a LPP state (as there is no proper synchronization),
** this function only sets a hook that, when called, will stop the
** interpreter.
*/
static void laction (int i) {
  int flag = LUA_MASKCALL | LUA_MASKRET | LUA_MASKLINE | LUA_MASKCOUNT;
  setsignal(i, SIG_DFL); /* if another SIGINT happens, terminate process */
  LPP_sethook(globalL, lstop, flag, 1);
}


static void print_usage (const char *badoption) {
  LPP_writestringerror("%s: ", progname);
  if (badoption[1] == 'e' || badoption[1] == 'l')
    LPP_writestringerror("'%s' needs argument\n", badoption);
  else
    LPP_writestringerror("unrecognized option '%s'\n", badoption);
  LPP_writestringerror(
  "usage: %s [options] [script [args]]\n"
  "Available options are:\n"
  "  -e stat   execute string 'stat'\n"
  "  -i        enter interactive mode after executing 'script'\n"
  "  -l mod    require library 'mod' into global 'mod'\n"
  "  -l g=mod  require library 'mod' into global 'g'\n"
  "  -v        show version information\n"
  "  -E        ignore environment variables\n"
  "  -W        turn warnings on\n"
  "  --        stop handling options\n"
  "  -         stop handling options and execute stdin\n"
  ,
  progname);
}


/*
** Prints an error message, adding the program name in front of it
** (if present)
*/
static void l_message (const char *pname, const char *msg) {
  if (pname) LPP_writestringerror("%s: ", pname);
  LPP_writestringerror("%s\n", msg);
}


/*
** Check whether 'status' is not OK and, if so, prints the error
** message on the top of the stack. It assumes that the error object
** is a string, as it was either generated by LPP or by 'msghandler'.
*/
static int report (LUA_State *L, int status) {
  if (status != LUA_OK) {
    const char *msg = LPP_tostring(L, -1);
    l_message(progname, msg);
    LPP_pop(L, 1);  /* remove message */
  }
  return status;
}


/*
** Message handler used to run all chunks
*/
static int msghandler (LUA_State *L) {
  const char *msg = LPP_tostring(L, 1);
  if (msg == NULL) {  /* is error object not a string? */
    if (LPPL_callmeta(L, 1, "__tostring") &&  /* does it have a metamethod */
        LPP_type(L, -1) == LUA_TSTRING)  /* that produces a string? */
      return 1;  /* that is the message */
    else
      msg = LPP_pushfstring(L, "(error object is a %s value)",
                               LPPL_typename(L, 1));
  }
  LPPL_traceback(L, L, msg, 1);  /* append a standard traceback */
  return 1;  /* return the traceback */
}


/*
** Interface to 'LPP_pcall', which sets appropriate message function
** and C-signal handler. Used to run all chunks.
*/
static int docall (LUA_State *L, int narg, int nres) {
  int status;
  int base = LPP_gettop(L) - narg;  /* function index */
  LPP_pushcfunction(L, msghandler);  /* push message handler */
  LPP_insert(L, base);  /* put it under function and args */
  globalL = L;  /* to be available to 'laction' */
  setsignal(SIGINT, laction);  /* set C-signal handler */
  status = LPP_pcall(L, narg, nres, base);
  setsignal(SIGINT, SIG_DFL); /* reset C-signal handler */
  LPP_remove(L, base);  /* remove message handler from the stack */
  return status;
}


static void print_version (void) {
  LPP_writestring(LPP_COPYRIGHT, strlen(LPP_COPYRIGHT));
  LPP_writeline();
}


/*
** Create the 'arg' table, which stores all arguments from the
** command line ('argv'). It should be aligned so that, at index 0,
** it has 'argv[script]', which is the script name. The arguments
** to the script (everything after 'script') go to positive indices;
** other arguments (before the script name) go to negative indices.
** If there is no script name, assume interpreter's name as base.
** (If there is no interpreter's name either, 'script' is -1, so
** table sizes are zero.)
*/
static void createargtable (LUA_State *L, char **argv, int argc, int script) {
  int i, narg;
  narg = argc - (script + 1);  /* number of positive indices */
  LPP_createtable(L, narg, script + 1);
  for (i = 0; i < argc; i++) {
    LPP_pushstring(L, argv[i]);
    LPP_rawseti(L, -2, i - script);
  }
  LPP_setglobal(L, "arg");
}


static int dochunk (LUA_State *L, int status) {
  if (status == LUA_OK) status = docall(L, 0, 0);
  return report(L, status);
}


static int dofile (LUA_State *L, const char *name) {
  return dochunk(L, LPPL_loadfile(L, name));
}


static int dostring (LUA_State *L, const char *s, const char *name) {
  return dochunk(L, LPPL_loadbuffer(L, s, strlen(s), name));
}


/*
** Receives 'globname[=modname]' and runs 'globname = require(modname)'.
*/
static int dolibrary (LUA_State *L, char *globname) {
  int status;
  char *modname = strchr(globname, '=');
  if (modname == NULL)  /* no explicit name? */
    modname = globname;  /* module name is equal to global name */
  else {
    *modname = '\0';  /* global name ends here */
    modname++;  /* module name starts after the '=' */
  }
  LPP_getglobal(L, "require");
  LPP_pushstring(L, modname);
  status = docall(L, 1, 1);  /* call 'require(modname)' */
  if (status == LUA_OK)
    LPP_setglobal(L, globname);  /* globname = require(modname) */
  return report(L, status);
}


/*
** Push on the stack the contents of table 'arg' from 1 to #arg
*/
static int pushargs (LUA_State *L) {
  int i, n;
  if (LPP_getglobal(L, "arg") != LUA_TTABLE)
    LPPL_error(L, "'arg' is not a table");
  n = (int)LPPL_len(L, -1);
  luaL_checkstack(L, n + 3, "too many arguments to script");
  for (i = 1; i <= n; i++)
    LPP_rawgeti(L, -i, i);
  LPP_remove(L, -i);  /* remove table from the stack */
  return n;
}


static int handle_script (LUA_State *L, char **argv) {
  int status;
  const char *fname = argv[0];
  if (strcmp(fname, "-") == 0 && strcmp(argv[-1], "--") != 0)
    fname = NULL;  /* stdin */
  status = LPPL_loadfile(L, fname);
  if (status == LUA_OK) {
    int n = pushargs(L);  /* push arguments to script */
    status = docall(L, n, LUA_MULTRET);
  }
  return report(L, status);
}


/* bits of various argument indicators in 'args' */
#define has_error	1	/* bad option */
#define has_i		2	/* -i */
#define has_v		4	/* -v */
#define has_e		8	/* -e */
#define has_E		16	/* -E */


/*
** Traverses all arguments from 'argv', returning a mask with those
** needed before running any LPP code or an error code if it finds any
** invalid argument. In case of error, 'first' is the index of the bad
** argument.  Otherwise, 'first' is -1 if there is no program name,
** 0 if there is no script name, or the index of the script name.
*/
static int collectargs (char **argv, int *first) {
  int args = 0;
  int i;
  if (argv[0] != NULL) {  /* is there a program name? */
    if (argv[0][0])  /* not empty? */
      progname = argv[0];  /* save it */
  }
  else {  /* no program name */
    *first = -1;
    return 0;
  }
  for (i = 1; argv[i] != NULL; i++) {  /* handle arguments */
    *first = i;
    if (argv[i][0] != '-')  /* not an option? */
        return args;  /* stop handling options */
    switch (argv[i][1]) {  /* else check option */
      case '-':  /* '--' */
        if (argv[i][2] != '\0')  /* extra characters after '--'? */
          return has_error;  /* invalid option */
        *first = i + 1;
        return args;
      case '\0':  /* '-' */
        return args;  /* script "name" is '-' */
      case 'E':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_E;
        break;
      case 'W':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        break;
      case 'i':
        args |= has_i;  /* (-i implies -v) *//* FALLTHROUGH */
      case 'v':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_v;
        break;
      case 'e':
        args |= has_e;  /* FALLTHROUGH */
      case 'l':  /* both options need an argument */
        if (argv[i][2] == '\0') {  /* no concatenated argument? */
          i++;  /* try next 'argv' */
          if (argv[i] == NULL || argv[i][0] == '-')
            return has_error;  /* no next argument or it is another option */
        }
        break;
      default:  /* invalid option */
        return has_error;
    }
  }
  *first = 0;  /* no script name */
  return args;
}


/*
** Processes options 'e' and 'l', which involve running LPP code, and
** 'W', which also affects the state.
** Returns 0 if some code raises an error.
*/
static int runargs (LUA_State *L, char **argv, int n) {
  int i;
  for (i = 1; i < n; i++) {
    int option = argv[i][1];
    LPP_assert(argv[i][0] == '-');  /* already checked */
    switch (option) {
      case 'e':  case 'l': {
        int status;
        char *extra = argv[i] + 2;  /* both options need an argument */
        if (*extra == '\0') extra = argv[++i];
        LPP_assert(extra != NULL);
        status = (option == 'e')
                 ? dostring(L, extra, "=(command line)")
                 : dolibrary(L, extra);
        if (status != LUA_OK) return 0;
        break;
      }
      case 'W':
        LPP_warning(L, "@on", 0);  /* warnings on */
        break;
    }
  }
  return 1;
}


static int handle_LPPinit (LUA_State *L) {
  const char *name = "=" LPP_INITVARVERSION;
  const char *init = getenv(name + 1);
  if (init == NULL) {
    name = "=" LPP_INIT_VAR;
    init = getenv(name + 1);  /* try alternative name */
  }
  if (init == NULL) return LUA_OK;
  else if (init[0] == '@')
    return dofile(L, init+1);
  else
    return dostring(L, init, name);
}


/*
** {==================================================================
** Read-Eval-Print Loop (REPL)
** ===================================================================
*/

#if !defined(LPP_PROMPT)
#define LPP_PROMPT		"> "
#define LPP_PROMPT2		">> "
#endif

#if !defined(LPP_MAXINPUT)
#define LPP_MAXINPUT		512
#endif


/*
** LPP_stdin_is_tty detects whether the standard input is a 'tty' (that
** is, whether we're running LPP interactively).
*/
#if !defined(LPP_stdin_is_tty)	/* { */

#if defined(LUA_USE_POSIX)	/* { */

#include <unistd.h>
#define LPP_stdin_is_tty()	isatty(0)

#elif defined(LUA_USE_WINDOWS)	/* }{ */

#include <io.h>
#include <windows.h>

#define LPP_stdin_is_tty()	_isatty(_fileno(stdin))

#else				/* }{ */

/* ISO C definition */
#define LPP_stdin_is_tty()	1  /* assume stdin is a tty */

#endif				/* } */

#endif				/* } */


/*
** LPP_readline defines how to show a prompt and then read a line from
** the standard input.
** LPP_saveline defines how to "save" a read line in a "history".
** LPP_freeline defines how to free a line read by LPP_readline.
*/
#if !defined(LPP_readline)	/* { */

#if defined(LUA_USE_READLINE)	/* { */

#include <readline/readline.h>
#include <readline/history.h>
#define LPP_initreadline(L)	((void)L, rl_readline_name="LPP")
#define LPP_readline(L,b,p)	((void)L, ((b)=readline(p)) != NULL)
#define LPP_saveline(L,line)	((void)L, add_history(line))
#define LPP_freeline(L,b)	((void)L, free(b))

#else				/* }{ */

#define LPP_initreadline(L)  ((void)L)
#define LPP_readline(L,b,p) \
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LPP_MAXINPUT, stdin) != NULL)  /* get line */
#define LPP_saveline(L,line)	{ (void)L; (void)line; }
#define LPP_freeline(L,b)	{ (void)L; (void)b; }

#endif				/* } */

#endif				/* } */


/*
** Return the string to be used as a prompt by the interpreter. Leave
** the string (or nil, if using the default value) on the stack, to keep
** it anchored.
*/
static const char *get_prompt (LUA_State *L, int firstline) {
  if (LPP_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2") == LUA_TNIL)
    return (firstline ? LPP_PROMPT : LPP_PROMPT2);  /* use the default */
  else {  /* apply 'tostring' over the value */
    const char *p = LPPL_tolstring(L, -1, NULL);
    LPP_remove(L, -2);  /* remove original value */
    return p;
  }
}

/* mark in error messages for incomplete statements */
#define EOFMARK		"<eof>"
#define marklen		(sizeof(EOFMARK)/sizeof(char) - 1)


/*
** Check whether 'status' signals a syntax error and the error
** message at the top of the stack ends with the above mark for
** incomplete statements.
*/
static int incomplete (LUA_State *L, int status) {
  if (status == LUA_ERRSYNTAX) {
    size_t lmsg;
    const char *msg = LPP_tolstring(L, -1, &lmsg);
    if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
      LPP_pop(L, 1);
      return 1;
    }
  }
  return 0;  /* else... */
}


/*
** Prompt the user, read a line, and push it into the LPP stack.
*/
static int pushline (LUA_State *L, int firstline) {
  char buffer[LPP_MAXINPUT];
  char *b = buffer;
  size_t l;
  const char *prmt = get_prompt(L, firstline);
  int readstatus = LPP_readline(L, b, prmt);
  if (readstatus == 0)
    return 0;  /* no input (prompt will be popped by caller) */
  LPP_pop(L, 1);  /* remove prompt */
  l = strlen(b);
  if (l > 0 && b[l-1] == '\n')  /* line ends with newline? */
    b[--l] = '\0';  /* remove it */
  if (firstline && b[0] == '=')  /* for compatibility with 5.2, ... */
    LPP_pushfstring(L, "return %s", b + 1);  /* change '=' to 'return' */
  else
    LPP_pushlstring(L, b, l);
  LPP_freeline(L, b);
  return 1;
}


/*
** Try to compile line on the stack as 'return <line>;'; on return, stack
** has either compiled chunk or original line (if compilation failed).
*/
static int addreturn (LUA_State *L) {
  const char *line = LPP_tostring(L, -1);  /* original line */
  const char *retline = LPP_pushfstring(L, "return %s;", line);
  int status = LPPL_loadbuffer(L, retline, strlen(retline), "=stdin");
  if (status == LUA_OK) {
    LPP_remove(L, -2);  /* remove modified line */
    if (line[0] != '\0')  /* non empty? */
      LPP_saveline(L, line);  /* keep history */
  }
  else
    LPP_pop(L, 2);  /* pop result from 'LPPL_loadbuffer' and modified line */
  return status;
}


/*
** Read multiple lines until a complete LPP statement
*/
static int multiline (LUA_State *L) {
  for (;;) {  /* repeat until gets a complete statement */
    size_t len;
    const char *line = LPP_tolstring(L, 1, &len);  /* get what it has */
    int status = LPPL_loadbuffer(L, line, len, "=stdin");  /* try it */
    if (!incomplete(L, status) || !pushline(L, 0)) {
      LPP_saveline(L, line);  /* keep history */
      return status;  /* cannot or should not try to add continuation line */
    }
    LPP_pushliteral(L, "\n");  /* add newline... */
    LPP_insert(L, -2);  /* ...between the two lines */
    LPP_concat(L, 3);  /* join them */
  }
}


/*
** Read a line and try to load (compile) it first as an expression (by
** adding "return " in front of it) and second as a statement. Return
** the final status of load/call with the resulting function (if any)
** in the top of the stack.
*/
static int loadline (LUA_State *L) {
  int status;
  LPP_settop(L, 0);
  if (!pushline(L, 1))
    return -1;  /* no input */
  if ((status = addreturn(L)) != LUA_OK)  /* 'return ...' did not work? */
    status = multiline(L);  /* try as command, maybe with continuation lines */
  LPP_remove(L, 1);  /* remove line from the stack */
  LPP_assert(LPP_gettop(L) == 1);
  return status;
}


/*
** Prints (calling the LPP 'print' function) any values on the stack
*/
static void l_print (LUA_State *L) {
  int n = LPP_gettop(L);
  if (n > 0) {  /* any result to be printed? */
    luaL_checkstack(L, LUA_MINSTACK, "too many results to print");
    LPP_getglobal(L, "print");
    LPP_insert(L, 1);
    if (LPP_pcall(L, n, 0, 0) != LUA_OK)
      l_message(progname, LPP_pushfstring(L, "error calling 'print' (%s)",
                                             LPP_tostring(L, -1)));
  }
}


/*
** Do the REPL: repeatedly read (load) a line, evaLPPte (call) it, and
** print any results.
*/
static void doREPL (LUA_State *L) {
  int status;
  const char *oldprogname = progname;
  progname = NULL;  /* no 'progname' on errors in interactive mode */
  LPP_initreadline(L);
  while ((status = loadline(L)) != -1) {
    if (status == LUA_OK)
      status = docall(L, 0, LUA_MULTRET);
    if (status == LUA_OK) l_print(L);
    else report(L, status);
  }
  LPP_settop(L, 0);  /* clear stack */
  LPP_writeline();
  progname = oldprogname;
}

/* }================================================================== */


/*
** Main body of stand-alone interpreter (to be called in protected mode).
** Reads the options and handles them all.
*/
static int pmain (LUA_State *L) {
  int argc = (int)LPP_tointeger(L, 1);
  char **argv = (char **)LPP_touserdata(L, 2);
  int script;
  int args = collectargs(argv, &script);
  int optlim = (script > 0) ? script : argc; /* first argv not an option */
  luaL_checkversion(L);  /* check that interpreter has correct version */
  if (args == has_error) {  /* bad arg? */
    print_usage(argv[script]);  /* 'script' has index of bad arg. */
    return 0;
  }
  if (args & has_v)  /* option '-v'? */
    print_version();
  if (args & has_E) {  /* option '-E'? */
    LPP_pushboolean(L, 1);  /* signal for libraries to ignore env. vars. */
    LPP_setfield(L, LUA_REGISTRYINDEX, "LPP_NOENV");
  }
  LPPL_openlibs(L);  /* open standard libraries */
  createargtable(L, argv, argc, script);  /* create table 'arg' */
  LPP_gc(L, LUA_GCRESTART);  /* start GC... */
  LPP_gc(L, LUA_GCGEN, 0, 0);  /* ...in generational mode */
  if (!(args & has_E)) {  /* no option '-E'? */
    if (handle_LPPinit(L) != LUA_OK)  /* run LPP_INIT */
      return 0;  /* error running LPP_INIT */
  }
  if (!runargs(L, argv, optlim))  /* execute arguments -e and -l */
    return 0;  /* something failed */
  if (script > 0) {  /* execute main script (if there is one) */
    if (handle_script(L, argv + script) != LUA_OK)
      return 0;  /* interrupt in case of error */
  }
  if (args & has_i)  /* -i option? */
    doREPL(L);  /* do read-eval-print loop */
  else if (script < 1 && !(args & (has_e | has_v))) { /* no active option? */
    if (LPP_stdin_is_tty()) {  /* running in interactive mode? */
      print_version();
      doREPL(L);  /* do read-eval-print loop */
    }
    else dofile(L, NULL);  /* executes stdin as a file */
  }
  LPP_pushboolean(L, 1);  /* signal no errors */
  return 1;
}


int main (int argc, char **argv) {
  int status, result;
  LUA_State *L = LPPL_newstate();  /* create state */
  if (L == NULL) {
    l_message(argv[0], "cannot create state: not enough memory");
    return EXIT_FAILURE;
  }
  LPP_gc(L, LUA_GCSTOP);  /* stop GC while building state */
  LPP_pushcfunction(L, &pmain);  /* to call 'pmain' in protected mode */
  LPP_pushinteger(L, argc);  /* 1st argument */
  LPP_pushlightuserdata(L, argv); /* 2nd argument */
  status = LPP_pcall(L, 2, 1, 0);  /* do the call */
  result = LPP_toboolean(L, -1);  /* get result */
  report(L, status);
  LPP_close(L);
  return (result && status == LUA_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}

